version: '3.9'

services:
  app:
    build: ./iksvan
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/scr/app
    ports:
      - '8000:8000'
    depends_on:
      - mysql
    env_file: .env
    environment:
      WAIT_HOSTS: mysql:3306
  mysql:
    image: mysql
    ports:
      - '3306:3306'
    env_file: .env
    restart: always
